### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by alexdown** [googlesamples/android-FingerprintDialog#1]
Hi,
almost all links mentioned in [README.md](https://github.com/googlesamples/android-FingerprintDialog/blob/master/README.md) are not working (return 404):
- https://developer.android.com/reference/android/hardware/FingerprintManager.AuthenticationCallback#onAuthenticationSucceeded%28%29.html
- https://developer.android.com/reference/android/hardware/FingerprintManager/index.html#authenticate%28%29.html
- https://developer.android.com/reference/android/security/KeyGenParameterSpec.Builder#setUserAuthenticationRequired%28%29.html
- https://developer.android.com/reference/android/security/KeyGenParameterSpec.html

**Comment by thagikura** [comment]
Thanks for the report. Javadoc references introduced in M preview are not live yet.
Once published, I'll check again the links are correct.

**Comment by jitendra7020** [comment]
Now Android 23 is live, please update the above links.

**Comment by thagikura** [comment]
Thanks for the reminder.

The links will be fixed in the next push.
