### ISSUE TITLE
How to do encryption and decryption?

### ISSUE THREAD

**Issue by riyaz** [googlesamples/android-FingerprintDialog#10]
How do I decrypt the string encrypted in this sample, when I use below code I get exception

```
SecretKey key = (SecretKey) mKeyStore.getKey(KEY_NAME, null);
mCipher.init(Cipher.DECRYPT_MODE, key);
String password = new String(mCipher.doFinal(encryptedStr), "UTF-8"));
```

```
java.security.InvalidKeyException: IV required when decrypting. Use IvParameterSpec or AlgorithmParameters to provide it.
```

Ok, I added IvParameterSpec like below but I get `Caller-provided IV not permitted` 

```

Encryption - throws exception

mCipher.init(Cipher.ENCRYPT_MODE, key, ivParams);


Decryption - returns null

byte[] iv = new byte[mCipher.getBlockSize()];
random.nextBytes(b);

IvParameterSpec ivParams = new IvParameterSpec(iv);

SecretKey key = (SecretKey) mKeyStore.getKey(KEY_NAME, null);
mCipher.init(Cipher.DECRYPT_MODE, key, ivParams);
byte[] output = mCipher.doFinal();

```

```
java.security.InvalidAlgorithmParameterException: Caller-provided IV not permitted when encrypting.
```

Any suggestions to decrypt the string encrypted using the sample in this example?

**Comment by thagikura** [comment]
Hi, 

Thanks for the report.
I ended up with the same result in AES/CBC transformation.

Let me check with other engineers and I'll update this thread.
Thanks.

**Comment by riyaz** [comment]
I managed to get this work by init with extra params.

```
                mCipher.init(Cipher.DECRYPT_MODE, key, mCipher.getParameters());

```

**Comment by thagikura** [comment]
Or found that,  you can omit the IV when you encrypt the data, then decrypting the data,
you can call getIv() to retrieve the random IV that it generated.
e.g. `cipher.init(Cipher.DECRYPT_MODE, key, new IvParameterSpec(encryptCipher.getIV()))`

At first you saw the exception "Caller-provided IV not permitted when encrypting.", you needed to disable the randomized encryption (see `KeyGenParameterSpec.Builder.setRandomizedEncryptionRequired`) if you provide an IV.

(Disabling the randomized encryption is not recommended, so not providing an IV when encrypting the data is recommended)

**Comment by riyaz** [comment]
Thanks it works.
