### ISSUE TITLE
requestPermissions is not needed

### ISSUE THREAD

**Issue by keiji** [googlesamples/android-FingerprintDialog#13]

**Comment by thagikura** [comment]
Hi,

Thanks for the report. But actually the issue title seems not correct, it works on Android 6.0, but requestPermissions is not needed (i.e. `onRequestPermissionsResult` is called with the condition the permissions is already granted).

Anyway, deleting the code calling `requestPermissions` looks fine. Let's discuss it at your pull request #14 

Thanks.

**Comment by keiji** [comment]
:+1:

**Comment by thagikura** [comment]
Fixed by #14
