### ISSUE TITLE
How to try it out?

### ISSUE THREAD

**Issue by akiranyc** [googlesamples/android-FingerprintDialog#2]
Thanks for this sample.
I just have a couple quick questions. What is the best way to try this out?
I don't think the emulator support the fingerprint reader and M Preview is only available on Nexus 5, 6, 9 and Nexus Player which don't have the reader also.
Does this sample work with any external fingerprint reader?
I assume isHardwareDetected returns true only if a build-in reader is available, right?
Thanks!

**Comment by thagikura** [comment]
Sorry I should have documented that in the README, but you should be able to mimic a touch of the fingerprint sensor on an emulator by 
`adb -s <emulator-ID> emu finger touch <fingerprint ID>`
e.g. `adb -s emulator-5554 emu finger touch 1`

With the Android M developer preview emulator, there should be the finger print settings in "Settings -> Security -> Fingerprint" where you can register a new fingerprint.

Please make sure you have the latest platform tools.
Also please let me know if the instructions don't work for you.

**Comment by thagikura** [comment]
You can also refer to this M preview overview document http://developer.android.com/preview/api-overview.html

**Comment by akiranyc** [comment]
@thagikura Cool Thanks! I should have read the document.

**Comment by thereisaway** [comment]
hey, there is no response after I typed adb -s emulator-5554 emu finger touch 1.

**Comment by captswag** [comment]
Got it working, if you are running windows you have to run telnet

> On Windows, you may have to run telnet 127.0.0.1 <emulator-id> followed by finger touch <finger_id>.

**Comment by DipaliTest** [comment]
There is no responce on emulator  after i typed adb -s emulator-5554 emu finger touch 1.

**Comment by captswag** [comment]
@DipaliTest Are you using windows? If so you have to run telnet 127.0.0.1 followed by finger touch <id>

**Comment by SharmileePatel** [comment]
On Windows, you may have to run telnet 127.0.0.1 followed by finger touch . But where to touch?

**Comment by captswag** [comment]
@SharmileePatel finger touch <id> is the command you write on the telnet prompt. No need of finger touch.

**Comment by collenndlovu** [comment]
on windows 
telnet 127.0.0.1 5554 
finger touch 1

**Comment by AndroidDeveloperLB** [comment]
@collenndlovu How do I use "telnet" command? It says it's not recognized...

**Comment by DASAR-zz** [comment]
@AndroidDeveloperLB  You have to enable or install Telnet client (Windows has it's own, but you must enable it):
http://windows.microsoft.com/en-GB/windows/telnet-faq#

Or you can install 3d party client (for example PuTTy support telenet connections)

**Comment by ChrisHan82** [comment]
I tried the adb command and it works

**Comment by ChrisHan82** [comment]
@akiranyc @thagikura @thereisaway Sometimes the adb command just stuck there. You have to keep injecting that command until it works on your AVM. You don't have to use the telnet even you are using windows.
