### ISSUE TITLE
Is it possible to identify multiple fingers?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [googlesamples/android-FingerprintDialog#20]
For example, if finger 1 is scanned do something, and if finger 2 is scanned, do something else?

**Comment by AndroidDeveloperLB** [comment]
BTW, the sample here
http://developer.android.com/samples/FingerprintDialog/index.html
 doesn't work like the reop here.

**Comment by thagikura** [comment]
Hi,

It's not possible. Registered fingerprints are treated equally.

**Comment by AndroidDeveloperLB** [comment]
Why ? It could be cool...
For example, I could set that each would do something else.
I could even make a gesture if the fingerprint sensor supports it... :(

**Comment by thagikura** [comment]
Because each registered fingerprint can unlock device for the account who registered the fingerprint equally. At least for now, these are treated as equally.

Maybe in the future, there is a change that identify multiple fingerprints. But current Android M doesn't support it.

**Comment by AndroidDeveloperLB** [comment]
Can you please consider adding it? 
It could even be cool as non-secure feature, so that for the foreground app, you could choose to have events for what happens for each type of finger.
It could also perform tasks via the lock screen itself : call a specific person, open Google,...

**Comment by mariotaku** [comment]
@AndroidDeveloperLB Actually it's possible (through hidden API). See [FingerprintManager.java#258](https://android.googlesource.com/platform/frameworks/base/+/marshmallow-release/core/java/android/hardware/fingerprint/FingerprintManager.java#258) .

**Comment by AndroidDeveloperLB** [comment]
Cool, but using it might break in future releases.

**Comment by dientm** [comment]
I am sorry for reopen this thread, I got a problem that I have to identify which fingerprint (registered) is scanned? For now I don't know is android support, or how to implement using hidden API? Can anyone give me an idea?

**Comment by mariotaku** [comment]
@dientm Using reflection.

**Comment by dientm** [comment]
@mariotaku: thank for your reply but actually I dont have to much experience with android. Can you show me some example of reflection in android?

**Comment by mariotaku** [comment]
@dientm https://code.tutsplus.com/tutorials/learn-java-for-android-development-reflection-basics--mobile-3203

**Comment by poongodi90** [comment]
@dientm  u did this multiuser fingerprint authentication?

**Comment by ZarSaeed** [comment]
Please tell me have you solved your issue if yes than how?

**Comment by sohambannerjee8** [comment]
I am also looking for this solution.

**Comment by AndroidDeveloperLB** [comment]
OK I wrote a suggestion about this here:
https://issuetracker.google.com/issues/112066297

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!

**Comment by AndroidDeveloperLB** [comment]
Thanks. Sadly it was closed to open a new one, so made it here:

https://issuetracker.google.com/issues/140661939
