### ISSUE TITLE
Can we use android-FingerPrintDialog with API less than API23 ? 

### ISSUE THREAD

**Issue by Elsobkey** [googlesamples/android-FingerprintDialog#22]
I'm trying to use this sample in android version less than android M , 
Noticing that there is a class called FingerPrintManagerCompat and FingerPrintManagerCompatAPI23
is this can do the same thing as the FingerPrintManager ?
If Yes , how to use it please (any reference)

thanks in advance ...

**Comment by thagikura** [comment]
No we can't. The minSdkVersion for this sample is 23.

If you want to use FingerrpintManager in apps whose API level is less than 23, you may consider using [FingerprintManagerCompat](http://developer.android.com/reference/android/support/v4/hardware/fingerprint/FingerprintManagerCompat.html), which behaves as if no fingerprint sensors are available with API level less than 23.
