### ISSUE TITLE
Problem checkPassword

### ISSUE THREAD

**Issue by moisesvs** [googlesamples/android-FingerprintDialog#23]
I am checking the source code of the fingerprintDialog and I saw the method checkPassword in the FingerprintAuthenticationDialogFragment class but this method isn't working because only checked if the password isn't empty and nothing else. 

My question is: This method should check the pin code of the phone, no?

Regards

**Comment by thagikura** [comment]
Hi, 

It may be a belated reply, but the checkPassword method in the FingerprintDialog is meant to check the app specific password for the user instead of the pin code of the phone.

If you want to check the pin code of the phone, you can use `KeyguardManager.createDeviceCredentialIntent`.

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
