### ISSUE TITLE
Enabling purchase button

### ISSUE THREAD

**Issue by NeerajaReddyKomma** [googlesamples/android-FingerprintDialog#24]
Hi,

I am using nexus 5 device.. I dnt have any option like finger print in settings. So not able to enable purchase  button.. Is there any particular to enable it.

**Comment by naddaf** [comment]
You can use the new (preview) version of the Android emulator; it has support for fingerprint.

**Comment by NeerajaReddyKomma** [comment]
I tried it is showing finger print screen not yet setup..  And showing like setings--> security--> finger print and setup the screen.

 But in settings i dnt have an option to setup fingerprint.

**Comment by naddaf** [comment]
If you use a Nexus 5X or 6P image with Api 23, you will have an option to
add fingerprint from settings (Settings -> Security)

On Tue, Dec 29, 2015 at 1:24 AM, NeerajaReddyKomma <notifications@github.com
