### ISSUE TITLE
ic_fp_40px icon non-commercial-friendly license

### ISSUE THREAD

**Issue by ghost** [googlesamples/android-FingerprintDialog#25]
The documentation for Android fingerprint API says "You must implement the user interface for the fingerprint authentication flow on your app, and use the standard Android fingerprint icon in your UI.",
which makes sense, to provide consistent UI across all apps and give users a recognizable cue when they can use the sensor.

However, the LICENSE here says "All image and audio files (including *.png, *.jpg, *.svg, *.mp3, *.wav 
and *.ogg) are licensed under the CC-BY-NC license",
which, as I understand, means the icon can't be used in commercial projects.

I find it unusual. Is this just an oversight?

**Comment by thagikura** [comment]
I can't comment on the CC-BY-NC license here, but you can find a fingerprint icon at the [Material icons](https://design.google.com/icons/#ic_fingerprint) site under the CC-BY license.

**Comment by ghost** [comment]
Ok, thank you!
