### ISSUE TITLE
Is it possible to ask user to enrol fingerprint if there are no fingers present for that user in the device?

### ISSUE THREAD

**Issue by iamnewspecies** [googlesamples/android-FingerprintDialog#26]
I want to invoke the fingerprint enrolment in the settings if there are no fingerprint enrolled. Is this possible?

**Comment by thagikura** [comment]
You can have the user jump to the security settings by 

```
context.startActivity(new Intent(Settings.ACTION_SECURITY_SETTINGS));
```

but I think there is no way to have the user jump to the fingerprint settings screen.
