### ISSUE TITLE
Build Failed with dagger

### ISSUE THREAD

**Issue by AkashMen10** [googlesamples/android-FingerprintDialog#27]
Build failed with below error:
Error:(43, 9) error: cannot find symbol method library()
Error:(44, 9) error: cannot find symbol method injects()
Error:(44, 19) error: illegal initializer for <none>
Error:Execution failed for task ':compileDebugJavaWithJavac'.

> Compilation failed; see the compiler error output for details.

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
