### ISSUE TITLE
Using Dependency Injection

### ISSUE THREAD

**Issue by EugeneHoran** [googlesamples/android-FingerprintDialog#29]
The fingerprint examples are good but I think it is bad practice to use Dependency Injections in a Google Sample(or any open-source sample). I am assuming most developers are not using DI in their applications or familiar with them (especially new developers). It is also recommended not to use DI frameworks.  [https://developer.android.com/training/articles/memory.html#DependencyInjection](url). Although it simplifies the code for the creator, it complicates code for individuals like myself that don't use DI.

**Comment by thagikura** [comment]
Thanks for the suggestion. The code internally already removed the DI dependency.
That will be reflected to this repository anytime soon.

**Comment by thagikura** [comment]
This is now fixed.
