### ISSUE TITLE
Dialog destroyed on rotation

### ISSUE THREAD

**Issue by alex-townsend** [googlesamples/android-FingerprintDialog#30]
The dialog fragment for the fingerprint authentication does not survive rotation, despite having setRetainInstanceState(true) set. This appears to be because the CancellationSignal does not emit the cancellation before the dialog fragment is recreated and resumed again -- mSelfCancelled = false then, causing mCallback.onError() to be called and to close the newly created dialog fragment to be dismissed.

Flow looks something like this (user selects Purchase to start):

1) FingerprintAuthenticationDialogFragment created:
- onResume() called -- mFingerprintUiHelper.startListening() called

2) User rotates device
- onPause() called -- mFingerprintUiHelper.stopListening() called (cancels CancellationSignal, sets mSelfCancelled = true)
- No messages sent through FingerprintManager.AuthenticationCallback during this time

3) New FingerprintAuthenticationDialogFragment created:
- onResume() and startListening() called -- setting mSelfCancelled = false
- **now we get a cancellation message in UI Helper's onAuthenticationError**, but I believe this cancel message is from the previous onPause() call

So it looks like the cancellation is not sent quickly enough on a rotation, causing the fragment created after the rotation to receive that cancellation message, which then closes the dialog fragment.

**Comment by alex-townsend** [comment]
Here's a log of the flow as well:

> 05-24 15:39:30.241 8110-8110/ D/DEBUG_TAG: startListening // Purchase pressed
> 05-24 15:39:39.811 8110-8110/ D/DEBUG_TAG: stopListening // Rotation happens
> 05-24 15:39:39.878 8110-8110/ D/DEBUG_TAG: startListening
> 05-24 15:39:39.882 8110-8110/ D/DEBUG_TAG: onAuthenticationError: errString: Fingerprint operation canceled. mSelfCancelled: false
> 05-24 15:39:40.110 8110-8110/ D/DEBUG_TAG: stopListening
> 05-24 15:39:40.203 8110-8110/ D/DEBUG_TAG: onAuthenticationError: errString: Fingerprint operation canceled. mSelfCancelled: true

**Comment by Kdoherty11** [comment]
+1

**Comment by nikhil-thakkar** [comment]
Late answer but I also found it the hard way.
The way it is handled is:
  
 ```
override fun onFingerprintAuthenticationError(errMsgId: Int, message: String) {
  if (errMsgId != android.hardware.fingerprint.FingerprintManager.FINGERPRINT_ERROR_CANCELED) {
      //do your thing
}
```

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
