### ISSUE TITLE
Where are the finger prints stored and can you access them? 

### ISSUE THREAD

**Issue by psikosen** [googlesamples/android-FingerprintDialog#32]

**Comment by thagikura** [comment]
Fingerprints data isn't exposed externally for security reasons.

The methods exposed in the [FingerprintManager](https://developer.android.com/reference/android/hardware/fingerprint/FingerprintManager.html) are the available methods externally.

**Comment by BuilderX** [comment]
Thanks for the speedy reply, do you know if google collects the fingerprint images?

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
