### ISSUE TITLE
crash after emulator reboot

### ISSUE THREAD

**Issue by Ghostish** [googlesamples/android-FingerprintDialog#33]
I was testing the sample app at Nexux 5x emulator. 
When I restart the app after rebooting the emulator, it crashed. 

In android monitor it read:

> java.lang.RuntimeException: java.security.InvalidAlgorithmParameterException: java.lang.IllegalStateException: At least one fingerprint must be enrolled to create keys requiring user authentication for every use

That's so weird . I checked the return value of `mFingerprintManager.hasEnrolledFingerprints()` ,which was true.  But the exception still was thrown during the `createKey()` .

**Comment by kdhiren** [comment]
i face the same problem.

**Comment by yakivmospan** [comment]
Still exists on emulate API 23, x86, 10th revision.

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
