### ISSUE TITLE
How come I can't press "Purchase" ?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [googlesamples/android-FingerprintDialog#34]
I do have a fingerprint scanner on my Nexus 5x. 
I just didn't set my lock screen to use it.
Why can't I have a fingerprint set for use on apps, yet not on the lock screen?

**Comment by thagikura** [comment]
Because you need to register at least one fingerprint and set up a lock screen (The APIs of the FingerprintManager expect so).

At this moment, registered fingerprints can unlock the device. There is no way to to register a fingerprint that can't unlock the lock screen.

**Comment by AndroidDeveloperLB** [comment]
But it makes no sense. Why can't apps be able to use fingerprints and get a unique identifier (based on their package names too, so that it won't be the same across apps), and use it as a way to unlock features and buy stuff?

Unlocking the device's lock screen is not the same as purchasing or unlocking private/protected content from the app. 

Anyway, I've written a request for this:
https://code.google.com/p/android/issues/detail?id=218972

I hope it will be added. Currently the fingerprint scanner API is very limited to just one scenario of using it only when it's set for lock screens...

**Comment by AndroidDeveloperLB** [comment]
Also, about this:
"There is no way to to register a fingerprint that can't unlock the lock screen."

I think it should be optional. I'd like to be able to unlock the lock screen using any fingerprint, just because it's easier than turning on the screen and then unlocking (or double tap to wake, which for some reason is still absent on Nexus devices) . Here's a request about it I wrote a while ago:
https://code.google.com/p/android/issues/detail?id=205820

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
