### ISSUE TITLE
How i insert the fingerprint in emulator if using window.

### ISSUE THREAD

**Issue by terrancelaw93** [googlesamples/android-FingerprintDialog#36]

**Comment by terrancelaw93** [comment]
It will show this sentences.

Assertion failed!
Program: C:\Users\user\AppData\Local\Android\Sdk\tools\qemu\windows-x86_64\qemu-system-i386.exe
File: ./android/skin/qt/tool-window.cpp, Line 405
Expression: mExtendedWindow
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

How to solve this problem.

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
