### ISSUE TITLE
CRASH: on save instance state exception 

### ISSUE THREAD

**Issue by br00** [googlesamples/android-FingerprintDialog#39]
Hi,
To make it crash do this:
- authenticate with your finger
- the animation with "Fingerprint recognised" text is shown
- because that animation has 1 sec of delay before calling the callback mCallback.onAuthenticated();
- if you send the app in background during the animation then it crash (just press home button before the animation is gone)

The issue is that are missing some checks when you call dismiss()

 @Override
    public void onAuthenticated() {
        // Callback from FingerprintUiHelper. Let the activity know that authentication was
        // successful.
        mActivity.onPurchased(true /\* withFingerprint */, mCryptoObject);
        dismiss();
    }

I suggest to put
Activity anActivity = getActivity();
if (getDialog() != null && getDialog().isShowing() && isResumed() && anActivity != null && !anActivity.isFinishing()) {
    dismiss();
}

or you can use dismissAllowingStateLoss()

**Comment by usantos** [comment]
If you use dismissAllowingStateLoss ()
would it be after the dismiss?

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
