### ISSUE TITLE
Is it working for samsung devices

### ISSUE THREAD

**Issue by DimaArts** [googlesamples/android-FingerprintDialog#40]
On samsung galaxy note 4 i have an registered fingerprint, but the app does not see it. Maybe samsung supports only their API.
![screenshot_2016-11-01-11-51-27](https://cloud.githubusercontent.com/assets/7409055/19884513/1e2973d2-a02b-11e6-8c00-6ef592d0294b.png)
![screenshot_2016-11-01-11-40-51](https://cloud.githubusercontent.com/assets/7409055/19884514/1e2f0856-a02b-11e6-915c-6b9e5d9f6259.png)

**Comment by samicodes** [comment]
Did you find any way to get it working on Samsung Note 4 ?

**Comment by JeffSaa** [comment]
Hi. Samsung have a own API for pringerprint function. You can found it here:
http://developer.samsung.com/galaxy/pass

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
