### ISSUE TITLE
Can realize the function of fingerprint puncher

### ISSUE THREAD

**Issue by zrtian** [googlesamples/android-FingerprintDialog#43]
Can realize the function of fingerprint puncher

**Comment by zrtian** [comment]
利用指纹sdk，可以将某些指纹信息与指定的账号信息进行绑定吗，类似与指纹打卡的功能？

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
