### ISSUE TITLE
Fingerprint permission

### ISSUE THREAD

**Issue by andris95** [googlesamples/android-FingerprintDialog#45]
Hello! In this sample project there is comment like this:

> Now the protection level of USE_FINGERPRINT permission is normal instead of dangerous.

But it is not true, in my project I am using compilseSdkVersion and targetSdkVersion 25.0.2.
And for example, to check if the device has a fingerprint sensor, i call this method:
`if (!mFingerprintManager.isHardwareDetected())`
and it says

> if (!mFingerprintManager.isHardwareDetected())

**Comment by yashasvigirdhar** [comment]
By Normal permission, it means that you can declare the permission in manifest and will be granted the same on app install. You don't need to request this permission at runtime. (All this applies for api >= 23 of course)

**Comment by LoPoBo** [comment]
I also saw this comment and found it confusing; has USE_FINGERPRINT ever been dangerous? I could not find any documentation supporting this.

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
