### ISSUE TITLE
Role of cryptoObject

### ISSUE THREAD

**Issue by yashasvigirdhar** [googlesamples/android-FingerprintDialog#46]
After going through the sample,

I am still curious about what is the use of passing `cryptoObject` to `authenticate` api of `FingerprintManager`.

If we see the code [here](http://androidxref.com/7.1.1_r6/xref/frameworks/base/core/java/android/hardware/fingerprint/FingerprintManager.java#477), it stores the reference to `cryptoObject` in a field which it uses only at one place : to create the `AuthenticationResult` when authenticatin succeeds (see [here](http://androidxref.com/7.1.1_r6/xref/frameworks/base/core/java/android/hardware/fingerprint/FingerprintManager.java#854)).

Also, apart from this, it uses the cryptoObject's `getOpId` method to set some `sessionId` that it passes to `authenticate` api of `IFingerprintService`. 

What's this `OpId`? I guess this is the thing that makes all difference, but I've no clue what it is and can't seem to find any documentation :-/ 

This question has been asked [here](https://stackoverflow.com/questions/44327885/android-fingerprint-authentication-role-of-cryptoobject), [here](https://stackoverflow.com/questions/34754889/android-cryptoobject-usage-in-fingerprint) and [here](https://stackoverflow.com/questions/34754889/android-cryptoobject-usage-in-fingerprint) but I didn't find a good answer in all the places.

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
