### ISSUE TITLE
Android Enterprise app not detecting any fingerprints

### ISSUE THREAD

**Issue by ruscles** [googlesamples/android-FingerprintDialog#48]
Hi,

I have an app that is developed to run inside the Android Enterprise container (for corporate devices). The fingerprint authentication from this sample works perfectly when the app is installed **outside** the enterprise container. However, when the app is running **inside** the container, it is unable to detect any fingerprints that the user registered outside the container (on the normal device).

It fails at this piece (line 137 of MainActivity):
```
if (!fingerprintManager.hasEnrolledFingerprints()) {
            // User hasn't enrolled any fingerprints to authenticate with
            Toast.makeText(this, "Go to 'Settings -> Security -> Fingerprint' and register at least one fingerprint", Toast.LENGTH_LONG).show();
            return;
        }
```

Is there a way to detect registered fingerprints outside the Enterprise container from an app that is running inside the container? I have tested this on an S7, S8, and Pixel. Thanks!

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
