### ISSUE TITLE
Deprecation Notice

### ISSUE THREAD

**Issue by fkirc** [googlesamples/android-FingerprintDialog#58]
To make it easier for the newcomers:
This library is deprecated since the release of the androidx library for the `BiometricPrompt` API.

If you want to combine the BiometricPrompt API with a symmetric key,
then you can have a look at this fully functional Kotlin implementation:
https://github.com/fkirc/secure-zip-notes/

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
