### ISSUE TITLE
Catch KeyPermanentlyInvalidatedException with Asymmetric key

### ISSUE THREAD

**Issue by BulatMukhutdinov** [googlesamples/android-FingerprintDialog#59]
When dealing with AES encryption we would get KeyPermanentlyInvalidatedException if new fingerprint was added.
Is it possible to detect fingerprints enrolments with asymmetric keys (RSA)?
I have tried but no success so far

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
