### ISSUE TITLE
Error in the code

### ISSUE THREAD

**Issue by AaronHsiao** [googlesamples/android-FingerprintDialog#6]
I got error in FingerprintUiHelper.java

```
mFingerprintManager.authenticate(cryptoObject, mCancellationSignal, 0 /* flags */, this, null);
```

Here are the error messages

```
Error:(86, 17) error: method authenticate in class FingerprintManager cannot be applied to given types;
required: CryptoObject,CancellationSignal,AuthenticationCallback,int
found: CryptoObject,CancellationSignal,int,FingerprintUiHelper,<null>
reason: actual and formal argument lists differ in length

Error:Execution failed for task ':Application:compileDebugJava'.
> Compilation failed; see the compiler error output for details.
```

How can I fix it ?
Thank you.

**Comment by thagikura** [comment]
Hi,

Just to make sure, are you using the [Develoepr Prview 2](https://developer.android.com/preview/support.html) version of Anroid M SDK?

The Android M SDK is still in a preview stage and the specification including method signatures may be subject to change.
Please make sure you are using the Developer Preview 2 version of Android M SDK.

**Comment by thagikura** [comment]
Hi,

Let me close this one since the question looks for the developer M preview SDK.
Please try it with the final Android M SDK.
