### ISSUE TITLE
Fingerprint question

### ISSUE THREAD

**Issue by gianlucainnocente** [googlesamples/android-FingerprintDialog#7]
Hi,
it is mandatory to register fingerprint inside my app? Or i can use also system registered fingerprints?

**Comment by thagikura** [comment]
Hi,

To clarify, a fingerprint can be registered system-wide. (There are no app-wide fingerprints)
But you need to use app-wide keys (both symmetric and asymmetric) that require a fingerprint authentication.
Because you need to set the `.setUserAuthenticationRequired` to `true` to a `KeyGenParameterSpec.Builder`, which system-wide keys (provided by the KeyChain API) doesn't support at this moment.

**Comment by gianlucainnocente** [comment]
"But you need to use app-wide keys (both symmetric and asymmetric) that require a fingerprint authentication."

So i need to authenticate only for the first time on my app?
Is it correct?

**Comment by thagikura** [comment]
It's not correct.

If you set the `.setUserAuthenticationRequired` to `true` the app users need to authorize every use of the created key.

**Comment by gianlucainnocente** [comment]
Have you ever tried the touch id on ios or the Samsung SPass ?
I want it to work in the same way...

So if the user has 4 fingerprints registered on the system, he can authenticate on my app with all of them.

Can i do it with Marshmallow fingerprint?

Thank you

**Comment by thagikura** [comment]
> Have you ever tried the touch id on ios or the Samsung SPass ?
> I want it to work in the same way...

Haven't tried it. What flow do you exactly want to achieve?

> So if the user has 4 fingerprints registered on the system, he can authenticate on my app with all of them.

To be precise, he can authenticate the use of the created key with all of them. It's up to you what you want to achieve (such as login, or online purchasing) that require user authentication in your app.
But if the user has 4 fingerprints registered, yes, the user can authenticate every use of the created key with all of them. (If a new fingerprint is added after the creation of the key, it's not true. The key needs to be re-created)
All registered fingerprints are considered as a valid credential of the user.

> Can i do it with Marshmallow fingerprint?

Sorry, what do you mean by this?

Thanks.

**Comment by gianlucainnocente** [comment]
When the user opens the app, it should ask for the finger.. The user put the finger on the sensor and the authentication success callback is fired.

Ok?

**Comment by thagikura** [comment]
I understand you want to use users fingerprints as credentials to log in to your app.
It's possible.

An example flow is like:
1. When the user first launch the app, have the user type their id and password
2. Create a symmetric key that requires user authentication
3. Encrypt the user's id and password using the symmetric key
4. Next time the user launches the app, prompt the user to touch the fingerprint sensor
5. If the authentication is successful, decrypt the id and password using the symmetric key in step 2, then log the user in.

**Comment by thagikura** [comment]
Hi,

Did my previous comment answer your question?
Thanks.

**Comment by thagikura** [comment]
Closing this. Please re-open the issue if you need further information.

Thanks.
