### ISSUE TITLE
Two questions related to device reboots and encryption

### ISSUE THREAD

**Issue by afollestad** [googlesamples/android-FingerprintDialog#8]
I have two questions:
1. If I register a fingerprint using the ADB command on a Nexus 5X emulator, it registers within the sample (well, a modified version). When the emulator is closed and started again, the fingerprint is still registered in the system settings but no longer registers with the sample. Is there cryptographic information that has to be saved and re-used in order for it to work after reboot?
2. The cipher in the sample is initialized and authenticated in encryption mode, it can be used to encrypt data after recognizing a fingerprint. If you initialize a cipher again in decrypt mode, does it have to be passed through the `FingerprintManager.authenticate()` method again to be fully initialized for decryption? In other words can you switch between encryption and decryption after scanning your finger once?

**Comment by thagikura** [comment]
As for the first one:
Short answer - No. The app user needs to use their registered fingerprint before every use of the created key.
Maybe a valid solution - There is `setUserAuthenticationValidityDurationSeconds` in the `KeyGenParameterSpec.Builder` class, which changes the duration of the time, within that duration the key can be used without user's another authorization (i.g. within that second from the last authorization, the user doesn't have to touch the fingerprint sensor) You can check the [ConfirmCredential sample](https://github.com/googlesamples/android-ConfirmCredential) that explains how to use that API.

As for the second one:
The Cipher can be used for both encrypting/decrypting without passing the `Cipher` again to `FingerprintManager.authenticate()` on the conditions that:
- You create a key for the purpose of both encrypting/decrypting (i.e. passing `KeyProperties.PURPOSE_ENCRYPT` and `KeyProperties.PURPOSE_DECRYPT` in the `KeyGenParameterSpec.Builder`)
- You set the `setUserAuthenticationValidityDurationSeconds` second
- The app user authorized the use of the key (touched the fingerprint sensor) within that second

Does that answer your questions?

**Comment by thagikura** [comment]
To follow up on the first one, I don't think the duration persist after a reboot, but after a reboot the user anyway unlocks the phone using their credential. From that point the duration of `setUserAuthenticationValidityDurationSeconds` starts. So you may provide similar user experience as if the duration persists after a reboot.

**Comment by afollestad** [comment]
That's all very helpful, thanks!

To add to the first one though, I meant fingerprints I added to the emulator system settings were no longer recognized after the device rebooted. Even though they were still listed in the system settings. 

Not sure if that's related to keys or an issue with using the ADB command and emulator.

**Comment by thagikura** [comment]
> To add to the first one though, I meant fingerprints I added to the emulator system settings were no longer recognized after the device rebooted

Ah ok. So what message do you get when you try to use that fingerprint? The fingerprints should be still used after a reboot.
It might be an issue of the emulator.

**Comment by afollestad** [comment]
It just doesn't get recognized. You're probably right that it's an issue with the emulator. Luckily I'll have a shiny new Nexus 5X in about a week to test it with 😀

Thanks for the help!

**Comment by arvindlaljaiswal** [comment]
Hi,
I have tried to work out the existing FingerPrintDialog sample(google sample) in emulator, It worked at the beginning, but when I am trying to execute the same it is throwing the following error.
 Caused by: java.security.InvalidAlgorithmParameterException: java.lang.IllegalStateException: At least one fingerprint must be enrolled to create keys requiring user authentication for every use.
The fingerprint ID is already registered from the terminal.

**Comment by thagikura** [comment]
@arvindlaljaiswal 

The issue is duplicate of #18.
I think it's an issue with the emulator. Sorry for the inconvenience.
